import { bigint, mysqlTable, text, int, decimal, smallint, varchar} from 'drizzle-orm/mysql-core';

export const pitches = mysqlTable('pitches',
  {
    id: bigint('id', {mode: 'number', unsigned: true}).primaryKey().autoincrement(),
    player_name: text('player_name').notNull(),
    batter: int('batter').notNull(),
    catcher: int('catcher').notNull(),
    pitch_type: text('pitch_type'),
    pitch_name: text('pitch_name'),
    release_speed: decimal('release_speed'),
    release_pos_x: decimal('release_pos_x'),
    release_pos_z: decimal('release_pos_z'),
    type: text('type').notNull(),
    balls: smallint('balls').notNull(),
    strikes: smallint('strikes').notNull(),
    events: text('events'),
    description: text('description').notNull(),
    zone: smallint('zone'),
    des: text('des'),
    stand: text('stand').notNull(),
    p_throws: text('p_throws').notNull(),
    hit_location: smallint('hit_location'),
    pfx_x: decimal('pfx_x'),
    pfx_z: decimal('pfx_z'),
    plate_x: decimal('plate_x'),
    plate_z: decimal('plate_z'),
    on_3b: int('on_3b'),
    on_2b: int('on_2b'),
    on_1b: int('on_1b'),
    game_pk: int('game_pk').notNull(),
    inning: smallint('inning').notNull(),
    inning_topbot: text('inning_topbot').notNull(),
    outs_when_up: smallint('outs_when_up').notNull(),
    at_bat_number: smallint('at_bat_number').notNull(),
    pitch_number: smallint('pitch_number').notNull(),
    home_score: smallint('home_score').notNull(),
    away_score: smallint('away_score').notNull(),
    bat_score: smallint('bat_score').notNull(),
    fld_score: smallint('fld_score').notNull(),
    post_away_score: smallint('post_away_score').notNull(),
    post_home_score: smallint('post_home_score').notNull(),
    post_bat_score: smallint('post_bat_score').notNull(),
    post_fld_score: smallint('post_fld_score').notNull(),
    vx0: decimal('vx0'),
    vy0: decimal('vy0'),
    vz0: decimal('vz0'),
    ax: decimal('ax'),
    ay: decimal('ay'),
    az: decimal('az'),
    sz_top: decimal('sz_top'),
    sz_bot: decimal('sz_bot'),
    effective_speed: decimal('effective_speed'),
    release_pos_y: decimal('release_pos_y'),
    spin_axis: smallint('spin_axis'),
    release_spin_rate: decimal('release_spin_rate'),
    release_extension: decimal('release_extension'),
    pitcher: int('pitcher').notNull(),
    fielder_2: int('fielder_2').notNull(),
    fielder_3: int('fielder_3').notNull(),
    fielder_4: int('fielder_4').notNull(),
    fielder_5: int('fielder_5').notNull(),
    fielder_6: int('fielder_6').notNull(),
    fielder_7: int('fielder_7').notNull(),
    fielder_8: int('fielder_8').notNull(),
    fielder_9: int('fielder_9').notNull(),
    if_fielding_alignment: text('if_fielding_alignment'),
    of_fielding_alignment: text('of_fielding_alignment'),
    delta_home_win_exp: decimal('delta_home_win_exp'),
    delta_run_exp: decimal('delta_run_exp'),
    bat_speed: decimal('bat_speed'),
    swing_length: decimal('swing_length'),
    bb_type: text('bb_type'),
    hc_x: decimal('hc_x'),
    hc_y: decimal('hc_y'),
    sv_id: int('sv_id'),
    hit_distance_sc: decimal('hit_distance_sc'),
    launch_speed: decimal('launch_speed'),
    launch_angle: decimal('launch_angle'),
    estimated_ba_using_speedangle: decimal('estimated_ba_using_speedangle'),
    estimated_woba_using_speedangle: decimal('estimated_woba_using_speedangle'),
    woba_value: decimal('woba_value'),
    woba_denom: decimal('woba_denom'),
    babip_value: decimal('babip_value'),
    iso_value: decimal('iso_value'),
    launch_speed_angle: text('launch_speed_angle')
  });

export const games = mysqlTable('games', 
  {
    game_pk: int('game_pk').primaryKey(),
    game_date: text('game_date').notNull(),
    game_type: text('game_type').notNull(),
    home_team: text('home_team').notNull(),
    away_team: text('away_team').notNull(),
    game_year: text('game_year').notNull(),
  });

export const players = mysqlTable('players', 
  {
    key_uuid: varchar('key_uuid', {length: 36}).primaryKey(),
    key_mlbam: int('key_mlbam').notNull().unique(),
    key_bbref_minors: text('key_bbref_minors'),
    name_last: text('name_last').notNull(),
    name_first: text('name_first').notNull(),
    name_given: text('name_given'),
    birth_year: smallint('birth_year').notNull(),
    birth_month: smallint('birth_month').notNull(),
    birth_day: smallint('birth_day').notNull(),
  });
